#!/bin/bash
# using the case command

case $USER in
badboy | rich)
	echo "welcome, $USER"
	echo "please enjoy your visit";;
hadoop)
	echo "Hey, Boy! $USER";;
jessica)
	echo "Do not forget to log off when you're done";;
*)
	echo "Sorry, you are not allowed here";;
esac
