#!/bin/bash
# basic for command 

for test in Alabama Alaska Arizona Arkansas California Colorado
do
	echo "The next state is $test"
done
echo "The last state is $test"
test=Connecticut
echo "Wait. now we're visiting $test"
