#!/bin/bash
# iterate through all the files in a directory

for file in /home/hadoop/*
do
	if [ -d "$file" ]
	then	
		echo "$file is a directory"
	elif [ -f "$file" ]
	then
		echo "$file is a file"
	else
		echo "I don't know the type of $file"
	fi
done
