#!/bin/bash
# testing the read command

echo -n "Enter your name: "
read name
echo "Hello $name, welcome to my program."

# testing the -p option
read -p "Please enter your age: " age
days=$[ $age * 265 ]
echo "That make you over $days old!"

# entering multiple variable
read -p "Enter your name: " first last
echo "Checking data for $last, $first..."


# testing the REPLY environment variable
read -p "Enter a number: "
factorial=1
for (( count=1; count <= $REPLY; count++ ))
do
	factorial=$[ $factorial * $count ]
done
echo "The factorial of $REPLY is $factorial"

